### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by Alekuso** [HastagGuigui/shellrhythm#1]
This is optional but using a `requirements.txt` file for installation of deps will be easier for the end user and will save time, offering the control of the version you wanna use.
So instead of doing `pip install . . . . .`, you can just do `pip install requirements.txt` and everything is ready.
It would be a nice addition.

**Comment by Alekuso** [comment]
In addition: you can removed some such as`math` or `json` since they are standard.

**Comment by HastagGuigui** [comment]
requirements.txt added, as well as informations on how to use it in README.md

Thanks for the idea!
