### ISSUE TITLE
Editor: Metadata window doesn't round up and selecting an unknown option causes a crash.

### ISSUE THREAD

**Issue by TheNachoBIT** [HastagGuigui/shellrhythm#10]
When accessing the Metadata, the list doesn't round up and tries to access unknown options if you continue going down.

![imagen](https://user-images.githubusercontent.com/43283743/211110685-b121d000-d24b-4d36-8e17-2f01ff451db3.png)

Pressing Enter in this stage causes an index out of range error, resulting a crash:

![imagen](https://user-images.githubusercontent.com/43283743/211111067-aa364be7-ce71-4f3d-a279-390dafa09eb9.png)

**Comment by HastagGuigui** [comment]
you're never gonna believe it
it's actually because the options limit is set to index 4 (but it's 0-indexed)

Fixed in next commit
