### ISSUE TITLE
Resizing to a really small screen causes a crash.

### ISSUE THREAD

**Issue by TheNachoBIT** [HastagGuigui/shellrhythm#11]
While loading, before the main menu shows up, if you resize it to a small size can cause the entire terminal to crash on you.

Screenshot taken a second after it crashes:

![imagen](https://user-images.githubusercontent.com/43283743/211111556-5f153e2e-a764-4b5d-89de-def8d3503e6b.png)

**Comment by TheNachoBIT** [comment]
Update: This can also happen in game aswell.

**Comment by HastagGuigui** [comment]
This issue seems to be Windows-specific, as I've been unable to replicate it on Linux.
![image](https://user-images.githubusercontent.com/47950669/211147486-4e2a267c-e49f-47a3-8592-cf0de606aa3a.png)
Will try and test it more later

**Comment by HastagGuigui** [comment]
Apparently, for some reason, on Windows, resizing a window to a height of 0 terminates the app instantly. 

https://user-images.githubusercontent.com/47950669/211149602-16d90091-6db2-498a-b52d-0dfcc4a93045.mp4

This issue therefore seems to not be related to the game itself.
