### ISSUE TITLE
Weird framebuffer issues after resizing.

### ISSUE THREAD

**Issue by TheNachoBIT** [HastagGuigui/shellrhythm#8]
Resizing the terminal can cause these kinds of issues.

![imagen](https://user-images.githubusercontent.com/43283743/211110043-df8a6f47-0100-4699-a251-3830af1a2d75.png)

This gets fixed when it goes from one entire window to another.

**Comment by HastagGuigui** [comment]
Fixed by clearing the screen every time the SIGWINCH signal is sent (aka the terminal is being resized), the only thing i need to fix is to add back the title screen logo once the screen has been cleared

Will be up next commit!

**Comment by HastagGuigui** [comment]
wait, i just realised the way i took it [is not compatible with windows](https://github.com/jquast/blessed/issues/131)

dammit

**Comment by HastagGuigui** [comment]
Found a workaround by checking for terminal size every loop cycle on Windows

**Comment by HastagGuigui** [comment]
ok im stupid and forgot since sigwinch doesn't exist on Windows it just crashes bru
