### ISSUE TITLE
Editor: Adding "Space" as a Key causes a crash.

### ISSUE THREAD

**Issue by TheNachoBIT** [HastagGuigui/shellrhythm#9]
Adding the "Space" Key as a Note causes this error:

![imagen](https://user-images.githubusercontent.com/43283743/211110463-94ad25e0-d459-46d1-9f87-5c66a0b6d9b5.png)

**Comment by HastagGuigui** [comment]
Fixed for next commit! It was a dumb mistake on my side that forgot to check if the key pressed was in the currently selected layout-
